env = "test" # "test", "dev", "prod"

[log]
# Log level: "trace", "debug", "info", "warn", "error"
level = "info"

[server]
# The address to bind to.
port = 8443
# cert file path to enable https, example: "/etc/https/mydomain.crt"
cert_file = "tests/jarvis.agent.crt"
# key file path to enable https, example: "/etc/https/mydomain.key"
key_file = "tests/jarvis.agent.key"
# client root cert file path to enable mutual tls, example: "/etc/https/clientroot.crt"
client_root_cert_file = "tests/ca.crt"
# The maximum number of seconds to wait for graceful shutdown.
graceful_shutdown = 10
